[build]
  base = ""          
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "https://nextwizard.netlify.app/:splat"
  status = 301
  force = true
  conditions = { Host = ["68e5626f0d34670008704a91--nextwizard.netlify.app"] }


[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Cache-Control = "no-store"